name: Check Environment Variables

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-env-vars:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Check environment variables
      id: check_env_vars
      run: |
        # Define expected values
        EXPECTED_API_URL=${{ secrets.EXPECTED_API_URL }}
        EXPECTED_API_KEY=${{ secrets.EXPECTED_API_KEY }}
        
        # Read the environment.ts file and extract values
        API_URL=$(grep -oP 'API_URL: "\K[^"]+' src/environments/environment.ts)
        API_KEY=$(grep -oP 'API_KEY: "\K[^"]+' src/environments/environment.ts)
        
        # Check if the values match the expected values
        if [ "$API_URL" != "$EXPECTED_API_URL" ]; then
          echo "API_URL does not match expected value."
          sed -i 's/API_URL: $API_URL/API_URL: $EXPECTED_API_URL/g' src/environments/environment.ts
        fi

        if [ "$API_KEY" != "$EXPECTED_API_KEY" ]; then
          echo "API_KEY does not match expected value."
          sed -i 's/API_KEY: $API_KEY/API_KEY: $EXPECTED_API_KEY/g' src/environments/environment.ts
        fi

        echo "All environment variables match the expected values."

