# .github/workflows/tagpr.yml
name: tagpr
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}